### ISSUE TITLE
TestFlight builds :)

### ISSUE THREAD

**Issue by yury** [holzschu/Carnets#1]
That would be easy to test and report bugs

**Comment by holzschu** [comment]
It's on the plan. I'd like to first remove a bug that prevents lauching the 5th or so notebook.

**Comment by yury** [comment]
Thank you!

**Comment by yury** [comment]
Just leave a link to the tweet here for the history.

https://mobile.twitter.com/nholzschuch/status/1095581517957529600

**Comment by holzschu** [comment]
Oh boy, I had forgotten this was the first issue!

**Comment by yury** [comment]
Oh, I didn't noticed it was #1 !!! Hehe
