### ISSUE TITLE
Invalid characters

### ISSUE THREAD

**Issue by drbaz** [holzschu/Carnets#106]
Hi there, i’m using Carnets Jupyter on my iPad and get an invalid character error when I surround strings with ‘ or “ from my standard iPad keyboard. Any suggestions to overcome this would be most welcome

**Comment by holzschu** [comment]
Hi, I think this is related to the "smart punctuation" settings in iOS, which turns your quotes into curly quotes. You might need to disable smart punctuation (in Settings -> General -> Keyboards).

**Comment by drbaz** [comment]
Yep that works. Thanks Nicolas
