### ISSUE TITLE
Pls add Opencv

### ISSUE THREAD

**Issue by girik-yo** [holzschu/Carnets#110]
I have trying to add opencv but it is not being installed. After surfing on net I found that only pure python libraries will work in Carnets. Could you please add support for Opencv?🙏🏻🙏🏻🙏🏻

**Comment by holzschu** [comment]
Hi, 
it is on the TODO list: https://github.com/holzschu/Carnets/projects/1

**Comment by girik-yo** [comment]
Ok. Thank You.

**Comment by holzschu** [comment]
Hi,
OpenCV made it to the AppStore version of Carnets.

**Comment by girik-yo** [comment]
Thanks. will definitely check it out.
