### ISSUE TITLE
Swift Compiler Errors

### ISSUE THREAD

**Issue by janwuyts** [holzschu/Carnets#12]
I'm trying to build this (full disclosure: first time I try anything in Xcode)

I'm getting these Swift Compiler Errors:

/Users/jan/github/Carnets/Carnets/ViewController.swift:120:13: Use of unresolved identifier 'clearAllRunningSessions'
/Users/jan/github/Carnets/Carnets/ViewController.swift:124:13: Use of unresolved identifier 'addRunningSession'
/Users/jan/github/Carnets/Carnets/ViewController.swift:125:17: Use of unresolved identifier 'numberOfRunningSessions'
/Users/jan/github/Carnets/Carnets/ViewController.swift:127:37: Use of unresolved identifier 'oldestRunningSession'
/Users/jan/github/Carnets/Carnets/ViewController.swift:150:13: Use of unresolved identifier 'removeRunningSession'
/Users/jan/github/Carnets/Carnets/ViewController.swift:212:9: Use of unresolved identifier 'clearAllRunningSessions'
/Users/jan/github/Carnets/Carnets/AppDelegate.swift:92:25: Use of unresolved identifier 'PythonFiles'
/Users/jan/github/Carnets/Carnets/AppDelegate.swift:253:82: Use of undeclared type 'DocumentBrowserViewController'

After just cloning the project from github, Xcode did not recognize the directory.
To solve this I started a new project and copied its `Carnets.xcodeproj` dir to the git clone.
I did add the frameworks to the project.

(I still need to figure out exactly what "change the developer key" means, I'm guessing this is related to getting it running on my ipad, not to compiling.)

Sorry in advance if these are just manifestations of my ignorance.
Thanks,

Jan.

**Comment by holzschu** [comment]
That is odd, and I'll look into it. All the functions you are missing are from `runningSessions.swift`, which is included in the repository and the Xcode project. 
Yes, the developer key is for running on the iPad. 
Then again, if you have trouble compiling, remember there is the easy way: send an e-mail and receive an invitation for TestFlight, that is install the pre-compiled version of the App on your iPad.
