### ISSUE TITLE
Arrow up and down between cells on smart keyboard

### ISSUE THREAD

**Issue by alchemyst** [holzschu/Carnets#13]
The arrow keys don't move between cells. I am aware there are buttons on the tool bar at the bottom to do this, but I've got years of muscle memory invested in those arrow keys.

**Comment by holzschu** [comment]
Definitely agree. It's on the todo list: 
https://github.com/holzschu/Carnets/projects/1
In the meantime, j and k work. It's not the same, but it's a keyboard replacement.
