### ISSUE TITLE
Issues report 

### ISSUE THREAD

**Issue by Sid281216** [holzschu/Carnets#133]
Hi

1/ I’ve just installed the latest version today and it seems like the « stop kernel » function still not working, also with ’i i’ (FYI I get to update PIP  to install new packages)
2/I’ve selected on ios settings Onedrive storage, but I still have folders created automatically on icloud and ipad storage it is normal ? I’ve re-installed all the app, when launching it again it re-created folders on ipad and icloud storage 
3/I also use Jupyerlab for windows, I do not know if it’s a bug: I create a .ipynb document with some codes in from jupyterlab on pc saved on Onedrive, when I open it on Carnets it shows me an empty document without any line of code..and vis-versa when I  create the document from Carnets 

You do a great job ! Best regards

**Comment by holzschu** [comment]
Hi, 
Thank you for reaching out. 
- Yes, you can not stop the kernel while it is running a task (I'll try to add it, but given the way iOS works, it is difficult to stop the kernel without stopping the server). You can, however, shutdown the kernel (in between tasks) and restart it. 
- Yes, iOS will create folders automatically on iCloud and iPad, even if you selected another storage. 
- OneDrive (and most of the other file providers) require application users to use their proprietary API (and often to pay a registration fee). Carnets works will all file providers that are accessible using the standard iOS API. OneDrive is not among these. Adding support to other file providers is high on the TODO list, but each of them requires me to read and understand their documentation and to add specific lines of code at multiple places. It's not easy.

**Comment by Sid281216** [comment]
Ok thanks for these informations ! For the last point, If I save my .iphnb documents in iCloud stockage it will work fine ?

**Comment by holzschu** [comment]
It should work fine, yes (as in: please let me know if it doesn't). We do not provide Jupyterlab (yet), so it will open using Jupyter Notebook instead.
