### ISSUE TITLE
iPad Pro: unable to store nb in dropbox

### ISSUE THREAD

**Issue by HKohlhoff** [holzschu/Carnets#139]
Hi,
I love the app, but can not really use it. I opened a nb from dropbox, edited it etc. But the changed nb is not stored on dropbox, what ever I try. 
Save as... asks for path within the iPad-file-System, but does not allow for folder in iCloud or DropBox. 

How do I store files where I want it to be?

When will DropBox be fully supported?

**Comment by holzschu** [comment]
Hi, 
we support all file providers that use iOS standard API (that includes iCloud, ShellFish and WorkingCopy). Dropbox, OneDrive, GoogleDrive all use proprietary API. I've tried several times to include support for them, but the documentation is lacking and it would require a lot of code to write. I'll keep trying, but it's unlikely to happen in the near future (I tried recently; it's really a scary task. Merely finding the relevant information requires navigating through a lot of documentation).

**Comment by HKohlhoff** [comment]
Thanks for the quick answer. I understand that it is quite a bit of work which may seem unnecessary, especially when it works with the standard APIs. Maybe there will be a time, when it become easier for you a developers to bind it to Dropbox etc. 
Because all my files reside on DropBox for my work at the university, there is no way for me right now.
