### ISSUE TITLE
Can’t exit Nbextensions config menu

### ISSUE THREAD

**Issue by jammin0921** [holzschu/Carnets#15]
Used edit drop down menu and then clicked __nbextensions config__. Clicked __more information__ at top to access the more information page. When going back, I can get back to the main Nbextensions congifuration menu but now I seem to be stuck in a loop and can’t get back to my notebook. Swiping left to right just reloads the nbextensions configurations page. Left arrow at top doesn’t seem to go back a page either.

**Comment by holzschu** [comment]
That was an amazing issue!
Explanation: the nbextension configuration menu loads http://localhost:8888/nbextensions/
which then loads http://localhost:8888/nbextensions/?nbextension=zenmode/main. Clicking on Readme then opens http://localhost:8888/nbextensions/nbextensions_configurator/rendermd/nbextensions/nbextensions_configurator/readme.md. So far, so good.

Going back the first time opens http://localhost:8888/nbextensions/?nbextension=zenmode/main, which is normal. 
Going back the second time opens http://localhost:8888/nbextensions/, which automatically opens http://localhost:8888/nbextensions/?nbextension=zenmode/main` and that's where we enter an infinite loop.

I changed the behaviour of the back button to avoid reloading the page if the path is the same, regardless of the query. The fix will be in the next build.
