### ISSUE TITLE
Find results I can click

### ISSUE THREAD

**Issue by hsarji** [holzschu/Carnets#150]
When I use Find and Replace, I can't click on the results. I researched the issue and found that some users prefer a web browser's find/replace for this reason. What can I do in Carnets? My goal in using Find and Replace isn't to replace text or syntax; rather, it's to find it so I can examine it further. If I can't navigate to the result, then Find and Replace in Carnets isn't useful for me. I hope there is a workaround. Thanks!

**Comment by holzschu** [comment]
I see what you mean. It's really frustrating. I'll see what i can do.

**Comment by hsarji** [comment]
Thank you. I hope you can create a solution. In the meantime, I figured out a workaround: I can use Textastic to open the file and to search the contents of a file. I can even edit the content in Textastic. Working with the text that way isn't pretty, but Carnets picks up the changes and I can continue working there.

**Comment by holzschu** [comment]
Hi,
Thanks again for the suggestion. There will be a 'Find' menu with clickable results in the next version (the 'Find and Replace' menu will also have clickable results, but sometimes you just want the "Find" interface).

**Comment by hsarji** [comment]
Thank you for this! I'm looking forward to the next version. Is it part of the beta? Is it possible to add a menu item that shows the word count? I used the code from the following link in a cell and I think it would be wonderful if we could just tap on a menu item to get the word count: <https://github.com/datamics/jupyter-word-count/blob/master/count-jupyter-nb-words.py#L1>

**Comment by hsarji** [comment]
Hi is the updated Find feature in version 1.5.6?

**Comment by holzschu** [comment]
Hi. Not yet, I'm still testing and debugging it.

**Comment by holzschu** [comment]
Hi, "Find" is now available on TestFlight: https://testflight.apple.com/join/yevwlUs1
It has the same interface as "Find and Replace", but you can click on the search results.

**Comment by hsarji** [comment]
Thank you. The "Find" works wonderfully. I can click on the search results. This is extremely helpful! I also like the keyboard shortcut, `G`. 

I'm wondering: When I click on the search result, it takes me to the cell. Is it possible to highlight the search term in the cell or place the cursor before that term?

**Comment by holzschu** [comment]
I made it so that it places the cursor just before the search term. If it doesn’t, then something is broken.

**Comment by hsarji** [comment]
I double checked. It does place the cursor before the search term, unless the term that is searched for is in an HTML comment and the cell is run (which means the HTML comment is hidden). In this case, clicking the search term exposes all of the contents of the cell. I need to run the search and tap on the result again to be taken to the word. 

Is it possible to make "Find" something like the table of contents panel so it persists after tapping on a result, instead of a dialog box that disappears after tapping on the result? 

I just want to thank you again for making the results in "Find" clickable. This feature is so helpful!
