### ISSUE TITLE
Location of snippets.json?

### ISSUE THREAD

**Issue by hsarji** [holzschu/Carnets#152]
I enabled Snippets in nbextensions. It seems to work since I can produce the following sample snippet from the menu. But how can I access `snippets.json` so I cad add my own snippets?

```
# This is an example snippet!
# To create your own, add a new snippet block to the
# snippets.json file in your jupyter nbextensions directory:
# /nbextensions/snippets/snippets.json
import this
```

**Comment by holzschu** [comment]
I think it's in `~/Library/Jupyter/nbextensions/snippets/snippets.json`. You'll need to copy it to a directory you can access with an external editor using a shell escape:
`!cp ~/Library/Jupyter/nbextensions/snippets/snippets.json ~/Documents/snippets.json`.

There is a possibility that these files get overwritten when the app gets updated, so it's a good idea to keep a copy in your home directory.

It's also possible that `~/Documents/.ipython/nbextensions/snippets/snippets.json`, if it exists, takes priority over the one in `~/Library/...`.

**Comment by hsarji** [comment]
Thank you! The following steps seem to work: 

1. `!cp ~/Library/Jupyter/nbextensions/snippets/snippets.json ~/Documents/snippets.json`
2. Edit the json file 
3. `!cp ~/Documents/snippets.json ~/Library/Jupyter/nbextensions/snippets/snippets.json`

Stopping at step 2 didn't work. But after step 3, I see that the new snippet is available. So, for the future, I can simply repeat steps 2 and 3.
