### ISSUE TITLE
Beta testing and Carnets local folder

### ISSUE THREAD

**Issue by hsarji** [holzschu/Carnets#156]
I'm now using the beta version of Carnets. The local folder for Carnets on my iPad seems to have disappeared because I cannot find it in the Files app and I cannot access it from Textmate or other apps. But when I ran `!ls ~/Documents/` in Jupyter, it listed my custom files: 

```
en_US_mod.dic	notebook.json	snippets.json
```

How can I access these files? For example, how can I open `en_US_mod.dic` now or add terms to it?

**Comment by holzschu** [comment]
I have seen that behavior before. It should reappear after a while. Sometimes, switching to a different file provider, then back to “on my iPad” forces the refresh. As you have seen, the documents are still there, but Files has not yet realized that the App has changed name.

**Comment by hsarji** [comment]
Thank you for your feedback. I switched to a different file provider and switched back. That didn't help. I restarted my iPad, and the Carnets folder reappeared.
