### ISSUE TITLE
Install OpenAI Gym

### ISSUE THREAD

**Issue by manut999** [holzschu/Carnets#159]
pip install gym gives you an error:

![8D4DA7EE-D912-4568-8BC2-ECF85BDB5BBA](https://user-images.githubusercontent.com/78268359/110241490-11a07280-7f49-11eb-8469-c2c31d6266d9.png)

**Comment by holzschu** [comment]
gym requires scipy, and scipy is not part of the AppStore install. You could try with the TestFlight version (https://testflight.apple.com/join/yevwlUs1) which has scipy on build 123 (but not builds 124-126). But if gym requires a C compiler, then it cannot be installed at the user level, only at the App developer level.

**Comment by manut999** [comment]
Ok thank you! How can I install 123? Testflight only offers my 124 to install...

**Comment by holzschu** [comment]
You should see something that says "Previous Builds" (below "Email Notifications"). From here, it's one of the builds for version 1.5.6.

**Comment by manut999** [comment]
Ok found it. Thx a lot!

**Comment by manut999** [comment]
Doesn‘t work, anyway...

![37755F83-634A-4417-8456-0605B26B26CE](https://user-images.githubusercontent.com/78268359/110242854-c89fec80-7f4f-11eb-9491-171ed8cf28ce.png)
![2D5BB199-F602-48E7-A912-1BC99EEFD846](https://user-images.githubusercontent.com/78268359/110242848-c50c6580-7f4f-11eb-8daa-8861716e3587.png)

**Comment by holzschu** [comment]
That's odd, because Pillow is already present. pip should not try to install it.

You can still try manual install: clone the repository (https://github.com/openai/gym.git) using WorkingCopy  (https://workingcopyapp.com), navigate to the cloned repository, create a notebook there and run `! pip install -e .`.

I'll try to add it to the TestFlight version as well.

**Comment by holzschu** [comment]
Ah, I see that gym installed with pip requires `Pillow<=7.2.0`, while Carnets provides Pillow version 8.1.2.
So the instructions become: 
- clone the repository (or download the archive)
- edit `setup.py` and replace 'Pillow<=7.2.0' with 'Pillow<=8.2.0' (line 32)
- create a notebook and run `! pip install -e .`

With that, gym is installed. I have no ways to test it. It will also be in the next TestFlight version, but with the time it takes to upload and the time it takes for Apple to approve, this will be available in roughly 2 days.

**Comment by manut999** [comment]
Ok got it working with your instructions above. I now tried to install gym[atari] which maybe uses C?
Thanks for your efforts!

![8CBE679F-9FB4-4819-9653-BFA3D8DFBB83](https://user-images.githubusercontent.com/78268359/110257015-d4150700-7f93-11eb-8a56-f415abc31010.png)
![E3507D19-0D35-4097-97FE-63487DF77457](https://user-images.githubusercontent.com/78268359/110257022-d7a88e00-7f93-11eb-838b-4f9b43566ea0.png)
![B6AADAF1-D92C-40DA-86DE-F277949C87D3](https://user-images.githubusercontent.com/78268359/110257023-d8d9bb00-7f93-11eb-81b7-ce8c4f12ee8a.png)
![F6963A04-BADA-4972-A821-DB329CB69AE4](https://user-images.githubusercontent.com/78268359/110257025-d9725180-7f93-11eb-9ab7-826dbf934555.png)
![DF629AE6-B0B0-437B-B84C-72C9372D73DA](https://user-images.githubusercontent.com/78268359/110257027-da0ae800-7f93-11eb-945a-d8a7d07b5375.png)

**Comment by holzschu** [comment]
I see at least OpenCV in here, which is a well known computer vision library, which will require a C compiler (it's already on the TODO list).
It also tries to install numpy version 1.19.3, instead of using the version 1.21 that is installed. cmake is a bad sign, too.

**Comment by manut999** [comment]
Gym in general works like a charm in 127! Thank you!

Some of the simulated games (e.g. CartPole-V0) seem to need OpenGL, see exception below. Is there any chance to install OpenGL, too?

...
Gym/gym/envs/classic_control/rendering.py in <module>
     25     from pyglet.gl import *
     26 except ImportError as e:
---> 27     raise ImportError('''
     28     Error occurred while running `from pyglet.gl import *`
     29     HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.

ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'

**Comment by holzschu** [comment]
The short answer is: "unfortunately, no". 

The long answer is that OpenGL never made it to portable devices, only OpenGL ES did (ES is for Embedded System). And Apple has stopped supporting OpenGL ES as well. I don't think it's going to be feasible in the near or medium future.

**Comment by manut999** [comment]
Ok, that’s a pity. But at least the text based OpenAI environments work. Thank again, I‘ll close that issue
