### ISSUE TITLE
Toggle if a line is commented out or not key shortcut

### ISSUE THREAD

**Issue by jammin0921** [holzschu/Carnets#17]
Have you thought about adding the (hardware) key shortcut to toggle if a line is commented out or not from anywhere within the line? I believe the command on a computer is: __Cmd + /__

I couldn’t find it in the user-editable key shortcuts. Thought I’d suggest it here. 

The app is looking and functioning very solid—it’s very impressive.

**Comment by holzschu** [comment]
ctrl+/ works with my external keyboard (cmd+/ does nothing). Can you try it?

**Comment by jammin0921** [comment]
That works well! Not sure how I missed that. Thank you!
