### ISSUE TITLE
Version 1.5.8 for iOS crashes on IphoneX 

### ISSUE THREAD

**Issue by poldo0964** [holzschu/Carnets#175]
Hi, thanks a lot for this wonderful app. Unfortunately, since I updated it earlier today, it systematically crashes before even fully loading. This is with IPhoneX and iOS 14.6. Can you advise ? Thank you.

**Comment by poldo0964** [comment]
Restarted phone and it worked.

**Comment by holzschu** [comment]
Thanks for reporting. I'm glad it was fixed, because I have no idea how to fix that.
