### ISSUE TITLE
Post to GitHub Gist

### ISSUE THREAD

**Issue by nipunbatra** [holzschu/Carnets#183]
There are some nice nbextensions like push a notebook to gist. It reduces the friction in sharing quickly with people. 

I wonder if it’s possible to add such a feature in Carnets. I think it could be done via either supporting nbextensions (and the corresponding GUI change) or a callback to working Copy.

**Comment by holzschu** [comment]
Carnets already supports nbextensions, so it's just a question of installing and activating the proper nbextensions.

**Comment by nipunbatra** [comment]
My bad! Extensions work perfectly! Sorry for the issue!
