### ISSUE TITLE
Conceivable to add glpk library?

### ISSUE THREAD

**Issue by devleaks** [holzschu/Carnets#185]
Hello,

First of all, many thanks for this wonderful handy tool that allow us to work on notebooks while not connected.

I’m using pm4py (process mining) and I’m stuck because on missing glpk (GNU linear programming kit). I tried to pip install the package but since it requires compilation and linking, I was out of luck. It is very unfortunate, because both cvxopt and PuLP are installed and their default install links with glpk, but glpk is not installed. 
So, would please it be possible to include glpk python package in a next release of Carnets Plus with Sci-py.
We may bump into other missing packages for pm4py down the road. Let me know if I can do something about it beforehand. I also understand pm4py could use PuLP which also relies on glpk, but I don’t feel like hacking pm4py to switch LP library.
Many thanks in advance.
Merci!
Best regards.
Pierre

**Comment by holzschu** [comment]
Hi, 
to the best of my knowledge, the official FSF position is still that any GPL licensed project is incompatible with distribution on the AppStore. I have tried to avoid including any GPL licensed project in my apps as a consequence.

I realize that the main case between AppStore distribution and GPL was with GPLv2, and GLPK is covered by GPLv3, and the situation might be different. However, a quick look on the internet does not give a definitive answer to that question, and I'm too small to take a risk that would involve lawyers and legal costs.

The FSF position does not extend to things you compile yourself and install on your own devices. So, if you have a Mac, and a bit of time, you can add GLPK to your own version of Carnets, and I'll help you do it (I realize that the conditions are very restrictive, and there's very little chance they apply to you. It's the best I can do).

**Comment by devleaks** [comment]
I would never suspect a license issue…
Yes, if needed, I learn how to make my very own private version of Carnets and I’ll call for help if necessary.
Many thanks for your prompt reply.
Best regards.
P.

**Comment by holzschu** [comment]
So, I've got some relatively good news: for another project (`libpysal`), I'm going to have to install `cbc`: https://github.com/coin-or/Cbc

So it seems you will get the requirements needed to install and run `pm4py` (in a while, cross-compiling these tools can take some time). 

I see `pm4py` also lists `graphviz` as one of the requirements, and I must warn you I haven't cross-compiled it either. It's also on the TODO list, but it seems impressive and difficult to cross-compile (there's lots of extra libraries).
