### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by weiszr** [holzschu/Carnets#2]
For testing, I tried to install several packages through pip install...it does not seem to work (See screenshot). Also the app crashes afterwards. Pretty awesome though!
![img_0072](https://user-images.githubusercontent.com/1410102/51965921-a6376d00-2473-11e9-84e5-8094506b1e6d.png)

**Comment by holzschu** [comment]
Appears to be solved:
![img_0131](https://user-images.githubusercontent.com/8070736/51994046-49a67300-24b0-11e9-8cc9-7741f65cc79f.PNG)

It's not necessarily the most elegant solution, but it works. pip is not well designed for placing packages in 2 different places.
