### ISSUE TITLE
Thanks for geopandas but mapclassify doesn’t install

### ISSUE THREAD

**Issue by wahlatlas** [holzschu/Carnets#204]
Geopandas works great. 
However, for Jenks Natural breaks and similar classification schemes, mapclassify is necessary, which I can’t get to install via pip.

**Comment by holzschu** [comment]
Mapclassify requires scipy. It is part of the default install on Carnets-with-scipy, but cannot be installed on Carnets.

**Comment by wahlatlas** [comment]
Thanks so much for the quick reply, works like Charme!
