### ISSUE TITLE
About variable inspector

### ISSUE THREAD

**Issue by natsu2424** [holzschu/Carnets#222]
Hello. I have recently started learning Python using this app, but when I enable the variable inspector in nbextensions, the screen does not display correctly. Is there any way to improve this?

**Comment by holzschu** [comment]
Hi,
I tried it briefly, and I couldn't identify the issue. Can you post a screenshot?

That being said, variable inspector assumes that you have a mouse available to resize the window or move it; it is a bit difficult to use with only a touchscreen.

**Comment by natsu2424** [comment]
Thanks for the reply. As you can see, the file name, the variable inspector button, and the menu do not appear, and adding a new cell does not display correctly. However, if I close the file once and reopen it, it displays correctly.
![image](https://user-images.githubusercontent.com/97967753/149971093-0c699583-73df-4e39-92e5-7a2a641c954f.png)
![image](https://user-images.githubusercontent.com/97967753/149971122-219fe8ad-805a-4923-86dc-5a7dd2199b16.png)

**Comment by holzschu** [comment]
I think variable inspector needs a restart from the server, so it's normal that it does not work the first time, even if it's a bit frustrating. It should be working from now on on all the files you open.

**Comment by holzschu** [comment]
Once it's activated, it should remain activated forever (if it doesn't, that's a bug).
