### ISSUE TITLE
Cannot import name warnings from matplotlib.pyplot

### ISSUE THREAD

**Issue by domi04** [holzschu/Carnets#224]
Hello, I was trying out the backtrader package which was installed without any problems. But when I try to run the example from the backtrader repository, it throws an error: ImportError: cannot import name 'warnings' from 'matplotlib.dates' (/private/var/containers/Bundle/Application/C9B292DD-07ED-4398-A1EC-D9D0AFFBE2CD/Carnets-sci.app/Library/lib/python3.9/site-packages/matplotlib/dates.py)

I'll add a screenshot, too

![image](https://user-images.githubusercontent.com/98167794/151666832-d35eb579-f100-4101-932d-0c442a20c61e.jpeg)

**Comment by domi04** [comment]
I also tried to import the warnings manually, but that didn't work.
Another solution I found online was to uninstall matplotlib and reinstall it with the version 3.2.2 as this one seems to not have the warnings issue but it's not possible to uninstall matplotlib.
I would be happy if you have any other ideas to help me and thanks in advance.

**Comment by holzschu** [comment]
Good question. We cannot go back to matplotlib 3.2, which is indeed an issue.
The issue has been fixed on backtrader repository (https://github.com/mementum/backtrader/pull/418), but the fix has not yet propagated to the pip repository. Probably the easiest path is to: 
- clone the backtrader repository (using either a-Shell or WorkingCopy)
- navigate there using the file selector, create a new notebook in that directory
- run "!python -m pip install ." or "!python setup.py install"

**Comment by domi04** [comment]
I'll try that. Thanks for the fast response, you've done a great job with Carnets!
