### ISSUE TITLE
Additional letter with code completion

### ISSUE THREAD

**Issue by domi04** [holzschu/Carnets#232]
Hi, 
I recently discovered that when I use the suggested code completion with enter the last letter I typed is added at the end of the completed code(see screenshots). It's not a big issue but it bothers me a little bit after some time. Is it possible to change that?
Thanks in advance :)
![image](https://user-images.githubusercontent.com/98167794/154332400-e22a9cb2-f43b-4e6e-bc52-e2e19b0e8d3e.png) 
![image](https://user-images.githubusercontent.com/98167794/154332562-b5ed961b-7cff-4acf-b86f-6021011fe35c.png)

**Comment by holzschu** [comment]
Thanks for raising this issue. I'll have a look.

**Comment by holzschu** [comment]
I think the issue is fixed in version 1.7.0?

**Comment by domi04** [comment]
It is, thanks!
