### ISSUE TITLE
TensorFlow MacOS for iPads with M1

### ISSUE THREAD

**Issue by zohairshafi** [holzschu/Carnets#245]
This might be a far shot, but do you think it would be possible to have Carnets with TensorFlow built for MacOS to utilize the inbuilt GPU on the M1? (https://developer.apple.com/metal/tensorflow-plugin/)

**Comment by holzschu** [comment]
Hi,
no, it won't work. Dynamic libraries contain specific code to prevent use on a different platform (you can't use Arm64 OSX libraries on Arm64 iOS phones).

**Comment by zohairshafi** [comment]
Aah I see, thanks!
