### ISSUE TITLE
Support Union/Optional from python 3.10

### ISSUE THREAD

**Issue by Mara-Li** [holzschu/Carnets#255]
Hello!
I use in my python code the new type annotation supported in 3.10 for union, eg `int|str`. But, it doesn't supported by Jupyter because it is python 3.9.

Do you think you will support it in some times ? Thanks.

**Comment by holzschu** [comment]
Hi,
the short answer is yes. I haven't had a request for 3.10 (and 3.11) features, but now I have.
The long answer is: it's a matter of months, not weeks.

The plan is:
- update all packages (soon-ish, there are already builds on TestFlight). This fixes a current bug with describe() in pandas.
- prepare for the switch to Notebook v7, as it changes a lot of things internally (almost ready, but the actual switch will still be interesting) (the timeline does not depend on me here)
- prepare for the switch to iOS 16 (over the summer)
- switch to python 3.10, or maybe go straight to 3.11 (we will likely be at candidate1 at this point) (after the summer)

**Comment by Mara-Li** [comment]
A lot of work here ! Good luck with that and thanks you for your reply :)
