### ISSUE TITLE
Cartopy problem

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#258]
I just downloaded v1.7.2 and attempted to !pip install cartopy. I got the following error message:

![image](https://user-images.githubusercontent.com/5650376/176957975-caefc18d-ba64-446d-9188-19d3633d14ae.png)

**Comment by ifuchs** [comment]
My bad. Cartopy was added to Carnets+ (not Carnets).

**Comment by holzschu** [comment]
Yes. Although cartopy does not formally require scipy, almost all practical uses do use scipy (for recomputing coordinates), so it made more sense to put it only in Carnets+.
