### ISSUE TITLE
Lower required iOS version to 14.0?

### ISSUE THREAD

**Issue by Bakr-Ali** [holzschu/Carnets#264]
Hello!

Could you please lower the required iOS version to 14.0?

I’m currently on iPadOS 14.4 and want to install this app but it says the minimum iOS version required is 14.5. I’m off by a single small update :(
I really want to stay on 14 for various reasons so I’d really appreciate if you lowered the required version a little.

**Comment by holzschu** [comment]
That is a good question. I am not certain that I can do it, though. But I'll give it a try. It will require creating and uploading a new version, so this is a matter of weeks, not days.

If your reasons for staying on 14.4 are that you have a low-power iPhone or iPad, you might be interested in a-Shell, an app by the same developer, with the same Python engine, but with a terminal-like interface. Using the command "ipython", you can have similar functionalities as Carnets, but with lower CPU usage.

**Comment by Bakr-Ali** [comment]
Thanks for considering it!

I have the first gen iPad Pro 9.7" (which is now considered low-power?) and wanted to stay on 14 because of reports of worse performance and battery life on 15 and up. Another reason is disliking the new home layout. It’s not that I wanted to stay on 14.4 specifically but more that once 15.0 came out, I can no longer update to any newer 14 version AFAIK.

I’ve just tried a-shell (and a-shell mini) to try the "ipython" command but they crash immediately on any command. I’ve reported it [here](https://github.com/holzschu/a-shell/issues/475).

**Comment by holzschu** [comment]
Hi, I forgot to come back to this issue, but the latest versions of Carnets have iOS 14.0 as a minimum requirement.
