### ISSUE TITLE
read URL yahoo finance

### ISSUE THREAD

**Issue by KenziTrader** [holzschu/Carnets#276]
I try to read an options chain from yahoo finance with `pandas_datareader`. Reading the URL fails with `b'Forbidden'`. I can open the URL in Safari. 

Do I need to do something special to give Carnets permission to open an URL?

Thanks,
Rene

![image](https://user-images.githubusercontent.com/6265927/212540216-3a462437-4523-4bd0-8a97-d0a275bc5467.jpeg)

**Comment by holzschu** [comment]
Carnets and Pandas can open URLs, so I think your problem is specific to Yahoo Finance.

Looking at open issues in pandas_datareader, I see this one, which is very similar: https://github.com/pydata/pandas-datareader/issues/923 
There is even a suggested fix: 
```python
FB = web.YahooOptions('FB')
FB.headers = {'User-Agent': 'Firefox'}
print(FB.expiry_dates)
```

**Comment by KenziTrader** [comment]
Yes, thanks, setting the user agent works.
