### ISSUE TITLE
error: 'xcfs': Invalid manifest

### ISSUE THREAD

**Issue by deniznet** [holzschu/Carnets#277]
Hello! 
I've tried to build Carnets for iOS. On ./get_frameworkds.sh got error:

Carnets % ./get_frameworks.sh 
error: 'xcfs': Invalid manifest
/Users/deniz/Downloads/Carnets/Carnets/xcfs/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
       ^

Xcode v14.2. What's wrong?

**Comment by holzschu** [comment]
Hi, 
I don't know for sure. Let me check and get back to you.

**Comment by deniznet** [comment]
> Hi,
> I don't know for sure. Let me check and get back to you.

Hi! Ok! What I should do?

**Comment by holzschu** [comment]
After checking, I do not know. "import PackageDescription" is part of the standard XCode install, so it should work. There is an (old) StackOverflow page with the same question, maybe some of the solutions could work for you: https://stackoverflow.com/questions/39795455/no-such-module-packagedescription

**Comment by deniznet** [comment]
> After checking, I do not know. "import PackageDescription" is part of the standard XCode install, so it should work. There is an (old) StackOverflow page with the same question, maybe some of the solutions could work for you: https://stackoverflow.com/questions/39795455/no-such-module-packagedescription

I've tried. So I opened project files in xcfs folder and build and run. It was successfully. Than I opened Carnets Xcode project, and I got errors (~2000) like


Showing Recent Messages
There is no XCFramework found at '/Users/deniz/Downloads/Carnets/Carnets/xcfs/.build/artifacts/xcfs/ios_system.xcframework'.

What I should do?

**Comment by holzschu** [comment]
Again, I do not know what is happening. I suspect an incomplete Xcode installation. What I can tell you:
- `./get_frameworks.sh` should run from the terminal without error. The error you had is not usual.
- once `./get_frameworks.sh` has successfully run, you should had frameworks inside `Carnets/xcfs/.buid/artifacts/xcfs/`

**Comment by deniznet** [comment]
Found solution! 
https://stackoverflow.com/questions/61501298/xcrun-error-unable-to-find-utility-xctest-not-a-developer-tool-or-in-path

I should change location for xcode:

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
