### ISSUE TITLE
Can’t View Code Suggestions

### ISSUE THREAD

**Issue by jammin0921** [holzschu/Carnets#28]
When pressing the _tab_ key to view code completion suggestions, you can see the first one (as in the attached image) but when you press the _..._, ellipsis, a list tries to pop up but then disappears before anything can be selected. It also seems like the list is not populated as well. 

I have attached a picture to describe what I mean. 

![IMG_0068](https://user-images.githubusercontent.com/33337632/58520659-5eed8e80-817e-11e9-9298-5d1dd53c2dd7.jpeg)

**Comment by holzschu** [comment]
Yes, I've noticed that too. Like the sliders in ipywidgets, this is standard javascript code that gets treated directly by WkWebView. I have no idea how to fix that (yet).

**Comment by holzschu** [comment]
It will be fixed in the next version. The only thing I'm not entirely happy with is that if you click outside the pop-up menu, it will insert the currently selected option.
