### ISSUE TITLE
Reset manually installed modules

### ISSUE THREAD

**Issue by Ohmagar** [holzschu/Carnets#284]
Yeah, I messed up a bit and installed things that weren’t pure python. 
i deleted the app and every data twice and deleted all my files connected with the app. 
All of the messed up modules are still there. 

Do you know of a way to reset my modules as if I downloaded the app for the first time? I don’t like having to „manually test out“ which of the modules are compatible to finally delete those again. 

Best regards.

**Comment by holzschu** [comment]
Hi,
the short answer is `!rm -rf ~/Library/lib/python3.11/site-packages/*`  (type this in a cell, it will remove all user-installed packages). This should make the app as if it was installed for the first time.

You can have a list of only user-installed packages with `pip list --user`.

**Comment by Ohmagar** [comment]
Thank you!
