### ISSUE TITLE
Some plotly plots do not work with Carnets browser settings

### ISSUE THREAD

**Issue by kalebmckale** [holzschu/Carnets#286]
After attempting to diagnose the reason why a particular plot was not displaying, I discovered the plots do appear in Chrome and Safari on the iPad. So, it appears that there’s some setting or feature that Carnets has accidentally left disabled in the built-in browser that’s preventing these plots from appearing.

Using one of Plotly’s examples is sufficient to see this:
### [3D Scatter Plot with Colorscaling and Marker Styling](https://plotly.com/python/3d-scatter-plots/#3d-scatter-plot-with-colorscaling-and-marker-styling)
```python
import plotly.graph_objects as go
import numpy as np

# Helix equation
t = np.linspace(0, 20, 100)
x, y, z = np.cos(t), np.sin(t), t

fig = go.Figure(data=[go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        color=z,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
)])

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig.show()
```

**Comment by holzschu** [comment]
I'll have a look.

**Comment by holzschu** [comment]
I ran the code, and I'm seeing the figure. 
The only difference I see is that I restarted the app after installing plotly.

**Comment by kalebmckale** [comment]
Yes, that is strange. It’s also interesting that the plots will show if the notebook is opened in either Safari or Chrome browsers, although it’s preferred to stay within the Carmen’s app. I’ll do some exploration on internet to see if other app devs have noticed differences between their apps on iPhone vs iPad.

**Comment by holzschu** [comment]
If you can connect a Mac to your iPad or iPhone, you can enable the "Develop" menu in Safari (https://support.apple.com/en-gb/guide/safari/sfri20948/mac), then inspect what is happening on every WebView on the iPad (and Jupyter notebooks are rendered in a WebView). It's a great debugging tool.

Here's what I have so far: 
- the HTML and JS code generated is identical on the iPhone and iPad (that's a relief)
- both generate SVG graphics, that is converted to WebGL somewhere.
- in the "Graphics" tab, I can inspect each graphics. The one that corresponds to the Plotly graphics is easy to spot.
- on the iPhone, I can inspect each GLSL program in this WebGL graphics. On the iPad, there's always one of them that has "There was an error retrieving this resource".

That is both good and bad: There is something wrong to be fixed, but I don't see (yet) how to fix it.

**Comment by holzschu** [comment]
Hi,
the latest TestFlight version of Carnets should work with plotly on iPad: https://testflight.apple.com/join/yevwlUs1

The change is small, but the impact are potentially wide-ranging, so I'm going to run more tests to check that it doesn't break something elsewhere.

**Comment by kalebmckale** [comment]
Looks good so far. Happy to try it out and report any problems.

**Comment by kalebmckale** [comment]
Shall I close this issue now?

**Comment by holzschu** [comment]
Yes, I think you can.
