### ISSUE TITLE
use of unresolved identifier 'ios_fork'; did you mean 'SYS_fork'

### ISSUE THREAD

**Issue by MobileAnalytics** [holzschu/Carnets#29]
Encountered following errors, where is the implementation of ios_fork() and ios_waitpid():
/Users/admin/Downloads/Carnets-master/Carnets/AppDelegate.swift:332:37: error: use of unresolved identifier 'ios_fork'; did you mean 'SYS_fork'?
                    var pid:pid_t = ios_fork()
                                    ^~~~~~~~
                                    SYS_fork
Darwin.SYS_fork:1:12: note: 'SYS_fork' declared here
public var SYS_fork: Int32 { get }
           ^
/Users/admin/Downloads/Carnets-master/Carnets/AppDelegate.swift:334:21: error: use of unresolved identifier 'ios_waitpid'; did you mean 'SYS_waitid'?
                    ios_waitpid(pid)
                    ^~~~~~~~~~~
                    SYS_waitid
Darwin.SYS_waitid:1:12: note: 'SYS_waitid' declared here
public var SYS_waitid: Int32 { get }

**Comment by holzschu** [comment]
Hi, 
I assume you are trying to compile the application.
`ios_fork` and `ios_waitpid` are both defined in `iOS_system`, but they have been added recently so they are not in the released version yet. 
If you really want to compile, you will have to clone `iOS_system` and compile it, then link the frameworks created with this project.
The Python frameworks in the release are also behind by several commits.
Most people are using the version on the AppStore these days.

**Comment by MobileAnalytics** [comment]
got it. thanks!
