### ISSUE TITLE
Replace an expression by another one.

### ISSUE THREAD

**Issue by Peter230655** [holzschu/Carnets#299]
Let's say I have a variable AX in my program and I want to change it to AL everywhere in the program.

Is there a simple way to do it?
Thanks a lot for any help!

**Comment by holzschu** [comment]
In the "Edit" menu, there is an option "Find and Replace". Does it answer your question?

**Comment by Peter230655** [comment]
Perfect, thanks!
I does not seem to distinguish between, say, AX and ax, but no big deal!
Thanks again!
