### ISSUE TITLE
Kernel Restart & Run All does not seem to work

### ISSUE THREAD

**Issue by weiszr** [holzschu/Carnets#3]
When I create a notebook and do a simple plotting of a sine function, then then wanting to run the all cells after restarting the kernel..nothing happens after the message ' Restart kernel and re-run the whole notebook?" clicking on "Restart and Run All Cells"

**Comment by holzschu** [comment]
Thank you. Added to the list of known bugs. Kernel shutdown followed by kernel restart works, though.

**Comment by holzschu** [comment]
Appears to be solved with commit ee4cdc7 
There is still an issue after roughlt 10 kernel restarts ("Too many files open")

The app is more stable with "clear all cells / run all" than with "restart kernel and re-run notebook".

**Comment by weiszr** [comment]
Will test later tonight. 

Cheers,

Robert
______________________________________________________________
Robert Weiss
Associate Professor of Natural Hazards
Department of Geosciences
Virginia Tech
4044 Derring Hall (0420)
Blacksburg, VA 24061, U.S.A.

Office: 1068A Derring
Phone:+1-540-231-2334
Fax: +1-540-231-3386

!!!!!Please note the new webpage!!!!!
http://coastalhazardsvt.weebly.com

Twitter: @VTCoastal

Albert Einstein (probably joking):
If the facts don't fit the theory, change the facts!
