### ISSUE TITLE
Add Pillow

### ISSUE THREAD

**Issue by tlockney** [holzschu/Carnets#30]
Attempting to install Pillow (a fork of PIL) results in an error since it depends on native libraries. Hoping it's possible to get this installed on Carnets.

**Comment by holzschu** [comment]
I'm already on it. It should be in build 41, expected to be in TestFlight this week and public release after that.

**Comment by tlockney** [comment]
Fantastic!

**Comment by holzschu** [comment]
You can now test Pillow in the TestFlight version: https://testflight.apple.com/join/yevwlUs1
I did not see any issues in my own tests, but let me know if somethings do not work for you.

**Comment by tlockney** [comment]
Thank you! I'll do some testing later today and report back.

**Comment by tlockney** [comment]
Looks like it's working great!
