### ISSUE TITLE
Plot image file save in Carnets Documents folder

### ISSUE THREAD

**Issue by goose-36** [holzschu/Carnets#322]
I am trying to save plot files as images. Part of my code includes reading csv/pkl files and also writing pkl files. For some reason, when I try to save an image file, it says the directory does not exist. 

I have recreated the issue using a basic sine plot instead of my actual data.

![image](https://github.com/holzschu/Carnets/assets/149157798/e18f97d7-6677-4ee5-b170-1bf6e4287c2b)

![image](https://github.com/holzschu/Carnets/assets/149157798/653a8f36-3919-48f3-b5ba-9e0bc819e4f1)

**Comment by holzschu** [comment]
Hi,
Thanks for the report and the images. I don't see an error in the second image, so I'm slightly confused.

My first take at reading the error message in the first image would be that `plot.savefig` does not expand the `~` in the file name, and I would try with local file saving: `plot.savefig("file")`.

**Comment by goose-36** [comment]
The second image was for clarity on the graph that I was trying to save.
Both images are of the same instance with different parts of the output
shown. Disregard it if that helps.

I have tried the full folder address for the iPad directory, but not just
putting a file name in like you've suggested. I will try that next.

I was hoping that I could start saving image files in various folders, but
if it won't work in the Carnets Plus root folder, I am not confident that
it would work for other folders.

Kind Regards,
Tom Haynes

**Comment by holzschu** [comment]
I think you could try expanding the tilde to the full path with `plot.savefig(os.path.expanduser("~/Documents/file"))`.

The full path should work, too, but it's subject to change at each app update.

**Comment by goose-36** [comment]
> I think you could try expanding the tilde to the full path with `plot.savefig(os.path.expanduser("~/Documents/file"))`.

This works. Thanks!
