### ISSUE TITLE
Building myself to add modules

### ISSUE THREAD

**Issue by isoboroff** [holzschu/Carnets#326]
Is there a README that explains building the project from source, and specifically the process of adding new packages?

I know the main page says to file an issue to request a package be built in, but I got to wondering if I could do this myself if I built the app from source.  But my Xcode-fu is not enough to figure out by reading the source.

Is it very difficult?

**Comment by holzschu** [comment]
It *is* very difficult. The main challenge is actually to build cpython (https://github.com/holzschu/cpython/), which is very difficult to setup for every single system (which Xcode version, which packages are installed locally,...) 

If the packages you aim for require scipy, you will need a Fortran compiler, and then it becomes impossible: there are no Fortran compiler for iOS, except the one I compiled myself from the gcc source code. When flang is released, I hope to make a more portable version of the code.

**Comment by isoboroff** [comment]
Thank you, that’s informative.
