### ISSUE TITLE
When importing korail2, I got an error, OSError in iPad 4th gen.

### ISSUE THREAD

**Issue by j-yschoi** [holzschu/Carnets#332]
I have no idea if it's an issue on Carnets or not.
Could you check the following issue?
I'm using Carnet Plus(Carnets -Jupyter (with scipy) V1.8.3) on iPad 4th gen.(iPadOS 17.5.1)
After executing the followings, I got an error

%pip install korail2
from korail2 import *

I got an error from importing as follows:
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython ~~~~

I don't see this error in both Linux box on Adroid and colab.
Thank you.

**Comment by holzschu** [comment]
Installing korail2 also installed the PyCryptodome package (it's one of the requirements). The PyCryptodome package contains multiple dynamic libraries, and iOS prevents loading dynamic libraries that are not part of the original app install. The error message you see is iOS trying to load the dynamic library associated with `Crypto.Cipher._raw_ecb`, and failing. 

a-Shell (another of my apps) has the PyCryptodome package already installed, so it might work better there.

**Comment by j-yschoi** [comment]
Thank you for immediate reply. I'll try it on a-Shell already installed on my iPad.
Thanks for the Carnet and a-shell app.
