### ISSUE TITLE
Not finding .py files

### ISSUE THREAD

**Issue by mpsjm** [holzschu/Carnets#38]
I’m trying to use Carnets for the first time, and I can open my .ipynb files, but I cannot get Carnets to either open or import .py files – I can see them in the file browser but they are greyed out.
I’m running Carnets 1.3.5 on an iPad Pro with iOS 12.3.1

I’m fairly sure this is a case of me doing it wrong, but I cannot work out what. 

Any ideas?

**Comment by holzschu** [comment]
You're not doing anything wrong ; Carnets is not designed (for the time being) to import python files in the notebook editor.

You can, however, create a Jupyter notebook next to the .py file, and type `%run file.py` or `%load file.py` from the notebook. 

You can also open the directory enclosing the python files (click "Select", then click the disk next to the directory, then click "Open") and access a text editor for all files inside the directory.

**Comment by mpsjm** [comment]
Thanks, that’s helped a lot. 

Awesome project by the way!
