### ISSUE TITLE
Ipywidgets

### ISSUE THREAD

**Issue by weiszr** [holzschu/Carnets#4]
Testing some more: pip install seems to work now, but using tqdm did not work. Googling around brought me to this issue (https://github.com/tqdm/tqdm/issues/394). Is there any chance that widgets are are problem for the “HBox(children=(IntProgress(value=0..” program that I receive when I try to use tqdm. There might be other PIpy affected by this. This might not be the most urgent issue

**Comment by holzschu** [comment]
Could you provide a small example of what you are trying to do? (with the packages required, and how it should look like). I will look into it.

**Comment by jammin0921** [comment]
@holzschu regarding this package (and future packages), what issues/concerns do you want to be made aware of? 

For example: 

When using _interact_ and using a slider, as shown below in **Picture 1**, the slider will slide while on Jupyter on a computer and change the value but not iPad/iOS -- there is no sliding functionality. However, when I select specific locations on the horizontal bar/slide on the iPad, it does change the value. Trying to "grab" the slider produces a zoom bubble as seen in **Picture 2** and there is no functionality to move the slider, it just moves the zoom bubble around.

**Picture 1 from Jupyter Notebook on Computer**
![Screen Shot 2019-03-20 at 1 16 45 AM](https://user-images.githubusercontent.com/33337632/54662979-d5e71680-4aad-11e9-9ac5-d115013a7caa.png)

**Picture 2 from Carnets on iPad**
<img width="1024" alt="ipywidgets - interact - slider zoom bubble" src="https://user-images.githubusercontent.com/33337632/54663597-cff23500-4aaf-11e9-95d1-0e9efe932d0e.png">

**Comment by holzschu** [comment]
Hi, 
Yes, it took me several hours to understant it. You have to click on the point where you want the slider to go, not on the slider itself. It comes from the iOS implementation of WebKit.
