### ISSUE TITLE
Add Astropy

### ISSUE THREAD

**Issue by petrushy** [holzschu/Carnets#40]
Hi, what a great app btw!

I would wish for including astropy, it has besides astronomical stuff a great unit conversion feature.

https://www.astropy.org/

Does not work to pip install it..

Many thanks

**Comment by holzschu** [comment]
Noted and added to the list.
Astropy depends on scipy according to https://astropy.readthedocs.io/en/stable/install.html, so it will be after scipy.

**Comment by wumpus** [comment]
scipy is optional, as the page you point at says.

my personal astropy-focused virtualenv only has numpy pulled in, which you already support.

I'm not enough of an astropy user to say if just numpy is typical or not.

**Comment by holzschu** [comment]
Thank you for pointing this out. I have now moved astropy ahead of scipy on the TODO list: https://github.com/holzschu/Carnets/projects/1 
It is now number 3 on the list.

**Comment by wumpus** [comment]
Thanks! If you let me know when it reaches TestFlight, I will organize some people to test out a variety of things.
