### ISSUE TITLE
Fails to restart kernel after screen locked

### ISSUE THREAD

**Issue by joshuali925** [holzschu/Carnets#41]
Open a notebook, type some code (!ls) and run, lock the screen (or press the home button). Wait about 30 seconds and return to the app. Its popup will say restarting server, and says "Connecting to kernel", "error" next to the menu. 

I tried restarting the kernel but still gives an error tag. Menus like Open, Save, Close, and the back button won't work. No code can be run and any modifications will be lost. It eventually says Not Connected in red, and the only way out is to kill the app and reopen. I'm on iOS 12.3.1.

**Comment by holzschu** [comment]
Noted. 
In my experiments, the bug is irregular: sometimes  the kernel does restart, others it doesn't.
Your post made me realize I have a way to detect and force restart.

**Comment by joshuali925** [comment]
Seems to be working now, closing the issue. Thank you for your work.

**Comment by holzschu** [comment]
To be honnest, I didn't do much on this front. It seems the improvement comes mostly from Apple improving things inside iOS and WKWebView.
