### ISSUE TITLE
Interactive graphs with %matplotlib notebook

### ISSUE THREAD

**Issue by bourdin** [holzschu/Carnets#45]
When using %matplotlib notebook magic, there doesn’t seem to be a way to interact with the graphics, use the zoom and pan buttons etc.

**Comment by holzschu** [comment]
Yes, I've noticed that too. I have no idea why. It also happens (for me) when visualizing a notebook on a distant server in Safari.
Widgets work, but that does not answer your question.

**Comment by bourdin** [comment]
it sounds like a bug in Jupyter or a compatibility issue with Safari. I will try to reproduce the issue outside of Carnets and report the bug. Thanks for your outstanding work.

**Comment by holzschu** [comment]
I've been investigating. It's not easy to change this: the touch events are intercepted by the system to zoom and pan the page instead of the graphics, and I haven't been able to prevent this (`stopPropagation()` and `preventDefault()` did not work). In addition, jQuery (used internally by matplotlib) does not have code for touch events at the moment.

I'll keep working on this, but I don't think there will be a working solution in the near future.

**Comment by bourdin** [comment]
I understand. I think that fixing this issue is well beyond the scope of carnets, at least in the short term, and should be given a very low priority.

**Comment by holzschu** [comment]
Hi, sorry to reopen this issue. 
The latest TestFlight version has bokeh installed, and with bokeh then pan and zoom tools are working. It's not exactly the answer to your question, but it is one answer. 
It also gives me hope to make it work with matplotlib at some point.

**Comment by bourdin** [comment]
Hi Nicolas,

Thanks for the update and the amazing work on carnets.

Blaise


On Feb 4, 2020, at 2:37 PM, Nicolas Holzschuch <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, sorry to reopen this issue.
The latest TestFlight version has bokeh installed, and with bokeh then pan and zoom tools are working. It's not exactly the answer to your question, but it is one answer.
It also gives me hope to make it work with matplotlib at some point.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fholzschu%2FCarnets%2Fissues%2F45%3Femail_source%3Dnotifications%26email_token%3DAABBJTOC42LTKZ77SP3DKODRBHGZDA5CNFSM4IPE7S3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKZDEJI%23issuecomment-582103589&data=02%7C01%7Cbourdin%40lsu.edu%7Cce305066809b4c50bedb08d7a9b2134c%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637164454610814652&sdata=Q%2BL3hgvj6JWukRGFq6OqWDr8wf6fnEmYhOAcB986WWA%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABBJTIEIEAQ5CRMF62RU7LRBHGZDANCNFSM4IPE7S3A&data=02%7C01%7Cbourdin%40lsu.edu%7Cce305066809b4c50bedb08d7a9b2134c%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637164454610823966&sdata=P6J5We8hxDAjOkkdbxf0LMrPxorOwBCr2VMO5tCLsng%3D&reserved=0>.

--
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin
