### ISSUE TITLE
iOS13.1 public beta 1&2 causes crash

### ISSUE THREAD

**Issue by d8nnii** [holzschu/Carnets#47]
I wanted to inform that I’ve been testing out the public beta of iOS and iPadOS 13 and it causes Carnet to crash upon launch for public beta 1 & 2. Please take a look.

**Comment by holzschu** [comment]
I think I can close this one, right?

**Comment by d8nnii** [comment]
Hi,

Yeah seems to be no crashes now. You can close this, thanks!


Best wishes, 
Danny Koh

> On 1 Oct 2019, at 12:08 AM, Nicolas Holzschuch <notifications@github.com> wrote:
> 

﻿
I think I can close this one, right?
