### ISSUE TITLE
When opening a URL from within a notebook, there seems to be no way to go back

### ISSUE THREAD

**Issue by nicolaschapados** [holzschu/Carnets#48]
When clicking on a link (e.g. from within a Python help text) within a notebook, it opens in the `Carnets` built-in browser. However, from that browser there seems to be no way to go back to the notebook itself. Tried every swipe and keyboard shortcut I could think of, to no avail. The only way is to kill `Carnets` and start again.

**Comment by holzschu** [comment]
In that situation, left-edge swipe should work (and right-edge swipe is forward)

**Comment by nicolaschapados** [comment]
Good observation — indeed it does. Thanks!

**Comment by holzschu** [comment]
It is a question that comes back frequently. I have added on the todo list to show a navigation toolbar when displaying a standard web page: https://github.com/holzschu/Carnets/projects/1
