### ISSUE TITLE
pd.read_clipboard() on iPad

### ISSUE THREAD

**Issue by zotko** [holzschu/Carnets#55]
The pandas function `read_clipboard()` doesn't function on iPad. Is it possible to fix it? Thank you!

**Comment by holzschu** [comment]
Hi, 
It appears to work on my side, but only if the clipboard contains something.

Could you provide a screenshot of the issue on your side?

**Comment by zotko** [comment]
Hi,
It works now. You can close this issue. Sorry for the trouble and thank you for a fast response.
