### ISSUE TITLE
Add “Open in Safari” or “Download HTML” option.

### ISSUE THREAD

**Issue by KivenChen** [holzschu/Carnets#56]
I would like to generate a PDF of a notebook for marking up. However, the following ways won’t work:

- Download PDF. `pandoc` is required so skip it.
- Open in Safari first. This will require a login token I can never find in Carnets.
- Download HTML. Same as `print preview` and “open in Safari”, the app will redirect to a page within the built-in web view. No way to export. Even screenshot wouldn’t treat it as a web page and show the “full page” tab.

**Comment by holzschu** [comment]
Thank you very much for this suggestion. I'l going to see how to make it work. Someone has suggested I install Jupytext (https://github.com/mwouts/jupytext ) which converts notebook to markdown or html files. It is very high on the list of features and it could be useful for your problem too.

**Comment by KivenChen** [comment]
Thanks for the suggestion. It’s now working perfectly in the local Carnets folder, where the generated documents can be saved.

**Comment by honzapulpan** [comment]
@KivenChen Could you please share how to install and use Jupytext in Carnets? I installed it with !pip install jupytext, but there is no option in menu, I can’t find how to use it.

**Comment by holzschu** [comment]
You need to quit Carnets and restart it, and then the option will appear in the File menu. 
See https://jupytext.readthedocs.io for the documentation.
