### ISSUE TITLE
White Screen / Lock Up Files > 600 KB

### ISSUE THREAD

**Issue by earlev4** [holzschu/Carnets#59]
Hi,

Good day! First off, I would like to extend my deepest appreciation and gratitude for the hard work behind this app; especially, kudos for making it open source. Thank you very much!

I am experiencing problems when opening .ipynb files that are greater than 600 KB. The screen immediately goes completely white and becomes unresponsive. Killing the app (double tap, slide up) and reopening the app does not seem to restore the app functionality. I had to delete and reinstall the app to restore functionality. I have tested the .ipynb file on other devices and software to confirm the file is not corrupt. I am running the latest version of IOS - 13.2.3. Any guidance would be greatly appreciated.

Thanks so much!

**Comment by holzschu** [comment]
Hi, 
thank you very much for reporting this issue. 
I have to say, this is not something I included in my battery of tests. Could you attach one example of these large .ipynb files that are causing the issue? 

Also, is left-edge-swipe working when the app displays the blank screen?

**Comment by earlev4** [comment]
Hi.

Thanks so much for the fast response. I really appreciate it. 

I am not sure how the file increased in size as the original file was around 93 KB and I do not recall any edits or even running the cells. However, I just opened the 700+ KB in Jupyter and Juno. I included the original file at 93 KB and the 700+ KB file in zip file. 
[pandas.zip](https://github.com/holzschu/Carnets/files/3884107/pandas.zip)

Also, left-edge-swipe does not seem to be working. 

Thanks so much for the assistance!

**Comment by holzschu** [comment]
Hi, 
there must be something wrong in the data transfer, because I get an "Error loading notebook: Notebook does not appear to be JSON". 
The file I have received begin with 
```
<!DOCTYPE html>
<html lang="en">
```
which explains the "Notebook does not appear to be JSON" error.

**Comment by earlev4** [comment]
Hi,

That is very strange. I just opened the file with Mouspad in Ubuntu and see the first few lines as:

```
{
 "cells": [

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [

```


I have tried attaching the file again with only the 700+ KB file in zip compression. 

Thanks so much!
[pandas-700kb.ipynb.zip](https://github.com/holzschu/Carnets/files/3884197/pandas-700kb.ipynb.zip)

**Comment by holzschu** [comment]
Hi, 
I have tried it, and it takes an incredibly long time to load but in the end it works. 

I am going to see if I can speed up the loading time for very large files, but there is very little documentation on that.

**Comment by earlev4** [comment]
Hi,

Good day! Thank you very much for looking at the issue. I really appreciate it. 

Also, a huge thanks to you for all your efforts on this project!

I will go ahead and close this issue.

Thanks so much!
