### ISSUE TITLE
ESC key functionality in Smart Keyboard 

### ISSUE THREAD

**Issue by 1stprinciples** [holzschu/Carnets#6]
I use ESC key while using Jupyter on my computer but Smart Keyboard doesn’t have an ESC key. So you gotta find a work around for that.

**Comment by holzschu** [comment]
Assuming I find a way to do that, which keys of the Smart Keyboard would you be ready to swap for the Escape key? Blinkshell uses CapsLock, but I'm not sure I can refer to it in JavaScript.

**Comment by 1stprinciples** [comment]
Cmd+~ maybe?

**Comment by iain2k** [comment]
Normally `Ctrl - [` or `⌘ .` will send ESC from the Smart Keyboard.    

I tried the Apple Magic keyboard which has an actual ESC key and that does not seem to work either when you try to change cell mode.

**Comment by alchemyst** [comment]
+1 on this issue, but I think the § key is almost never used on the smart keyboard and is in the "normal" escape key position.

**Comment by holzschu** [comment]
For those interested: I finally found a way to work on this issue. I'm still ironing bugs, but the option to remap caps-lock to escape should be in the next version.
