### ISSUE TITLE
Issue with connection.pool

### ISSUE THREAD

**Issue by barelyherenorthere** [holzschu/Carnets#61]
Hi, 

I was using Carnets to run my code. I'm still quite new to Python and coding. I have this particular code which I am able to run using Jupyter on my desktop. I import the following packages: 

import requests
import json
import urllib.parse
import numpy
import pandas

Basically, my code pulls data from a platform's API in JSON format, then arrange the JSON into a dataframe. However, when I run the code, I keep running into this error:
urllib3/connectionpool.py:847

I saw some python documentations that one way to overcome this was to do the following:
import urllib3
urllib3.disable_warnings()

I tried doing that, and true enough, my code ran perfectly.

Just wanna find out what this issue was caused by and if there's any danger if I use disable_warnings

thanks!

**Comment by holzschu** [comment]
Hi, 
I can't see the error in the report. It was probably removed by the markdown formatting. Can you make it visible?

**Comment by barelyherenorthere** [comment]
![photo_2019-12-01_12-05-36](https://user-images.githubusercontent.com/58306101/69909239-f801a880-1432-11ea-9679-d0d7aeb6ac82.jpg)

Hi, this was my error

**Comment by holzschu** [comment]
Thank you very much.

I looked into it, and the most likely explanation is that the connection is established, it is secure, but the method to verify whether it is secure is not compatible with iOS limitations. Hence the warning. 

You can disable the warning with `urllib3.disable_warnings()`, or leave it: it doesn't affect the result of the code.

iOS limitations prevent me from verifying the connection, but they also prevent attackers from doing anything dangerous.

**Comment by barelyherenorthere** [comment]
good to know. thank so much for looking into it!
