### ISSUE TITLE
SciPy and Pyto

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#68]
I know that many folks would love to see SciPy implemented in Carnets and my understanding is that it is complicated due partly to the fact that parts of SciPy use a FORTRAN. Pyto, which is available as open source on Github is a Python 3.8 app that includes SciPy. Is it possible to take advantage of this to bring SciPy, and possibly other modules, to Carnets?

**Comment by holzschu** [comment]
I'm afraid that Pyto will not substantially speed up the development of SciPy in Carnets.

Just running a module is a small part of the work required to make it work in Carnets. The hard part is tracking memory allocation and making sure everything is released when the module is released, and variables are reset to their original values.

**Comment by ifuchs** [comment]
Thanks. Good to know.
