### ISSUE TITLE
Seaborn

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#75]
I tried to install the data visualization package seaborn with !pip install seaborn but there is no output and it does not seem to terminate. Am I not waiting long enough (several minutes)?

**Comment by holzschu** [comment]
seaborn requires scipy, so it was not going to work anyway, but it should terminate with an error, not take forever to terminate. I'm looking into it.

**Comment by holzschu** [comment]
The bug that it does not seem to terminate should be fixed with build 65 (soon to be on TestFlight), which gives more progressive response from shell escape commands.

(The issue with seaborn itself will have to wait until scipy has been installed.)

**Comment by holzschu** [comment]
seaborn is now part of "Carnets with scipy", available on the AppStore: https://apps.apple.com/fr/app/carnets-jupyter-with-scipy/id1559497253
I am closing this issue.
