### ISSUE TITLE
Use or add git support 

### ISSUE THREAD

**Issue by oleksis** [holzschu/Carnets#87]
Is there a possibility to integrate git in Carnets? Some packages like nbdev use the subprocess module to use git. What would you recommend?

**Comment by holzschu** [comment]
Integrating git inside Carnets is difficult (it is a large software, with lots of system calls; there are also licensing issues). [WorkingCopy](https://workingcopyapp.com) is the best iOS port of git, but it is not integrated into the command line.

**Comment by oleksis** [comment]
I've seen you recommend [@WorkingCopyApp](https://twitter.com/WorkingCopyApp), I'll give it a try when I can. Thanks for the recommendation.
